# Generated by Django 5.0.7 on 2024-07-25 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Casas',
            fields=[
                ('id_casas', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Colegio',
            fields=[
                ('id_colegio', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id_curso', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Familias',
            fields=[
                ('id_familia', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_papa', models.CharField(max_length=255)),
                ('apellido_papa', models.CharField(max_length=255)),
                ('dni_padre', models.CharField(max_length=255)),
                ('domicilio_papa', models.CharField(max_length=255)),
                ('celular_papa', models.CharField(max_length=255)),
                ('telefono_papa', models.CharField(max_length=255)),
                ('ocupacion_papa', models.CharField(max_length=255)),
                ('email_papa', models.CharField(max_length=255)),
                ('nombre_mama', models.CharField(max_length=255)),
                ('apellido_mama', models.CharField(max_length=255)),
                ('dni_mama', models.CharField(max_length=255)),
                ('domicilio_mama', models.CharField(max_length=255)),
                ('celular_mama', models.CharField(max_length=255)),
                ('telefono_mama', models.CharField(max_length=255)),
                ('ocupacion_mama', models.CharField(max_length=255)),
                ('email_mama', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id_materia', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Nacionalidad',
            fields=[
                ('id_nacionalidad', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(default='Argentina', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Sexo',
            fields=[
                ('id_sexo', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(default='M', max_length=255)),
            ],
        ),
    ]
