# Generated by Django 5.0.7 on 2024-07-29 20:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colegio', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoriaprofesores',
            fields=[
                ('id_categorias', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('id_localidad', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(default='Capital', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Nivelprofesores',
            fields=[
                ('id_nivel', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='curso',
            name='color',
            field=models.CharField(default='Azul', max_length=7),
        ),
        migrations.CreateModel(
            name='Alumnos',
            fields=[
                ('id_alumno', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=50)),
                ('Apellido', models.CharField(max_length=50)),
                ('DNI', models.CharField(max_length=10)),
                ('Correo_Electronico_particular', models.EmailField(blank=True, max_length=254)),
                ('Correo_Electronico', models.EmailField(blank=True, max_length=254)),
                ('Direccion', models.CharField(max_length=100)),
                ('Fecha_de_Nacimiento', models.DateField()),
                ('Lugar_de_nacimiento', models.CharField(max_length=100)),
                ('estado_dispositivos', models.CharField(max_length=50)),
                ('Casas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colegio.casas')),
                ('Colegio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colegio.colegio')),
                ('Nacionalidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colegio.nacionalidad')),
                ('Sexo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colegio.sexo')),
                ('id_familia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colegio.familias', verbose_name='Apellido de la Familia')),
                ('Localidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colegio.localidad')),
            ],
        ),
        migrations.CreateModel(
            name='Docentes',
            fields=[
                ('id_docentes', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('apellido', models.CharField(max_length=255)),
                ('cuil', models.CharField(max_length=255)),
                ('legajo_administrativo', models.CharField(max_length=255)),
                ('legajo_reloj', models.CharField(max_length=255)),
                ('horario', models.CharField(max_length=255)),
                ('titulo_base', models.CharField(max_length=255)),
                ('fomacion_academica', models.CharField(max_length=255)),
                ('celular_mama', models.CharField(max_length=255)),
                ('correo_electronico_personal', models.CharField(max_length=255)),
                ('correo_electronico_institucional', models.CharField(max_length=255)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colegio.categoriaprofesores', verbose_name='Categoria')),
                ('cursos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colegio.curso', verbose_name='Cursos')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colegio.materia', verbose_name='Materias')),
                ('nivel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colegio.nivelprofesores', verbose_name='Nivel')),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioRol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(max_length=100)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
