# Generated by Django 5.0.7 on 2024-07-30 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colegio', '0002_categoriaprofesores_localidad_nivelprofesores_and_more'),
    ]

    operations = [
    ]
