# Generated by Django 5.0.7 on 2024-08-16 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colegio', '0002_categoriaprofesores_localidad_nivelprofesores_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notas',
            name='id_cursomateria',
        ),
        migrations.RemoveField(
            model_name='materiaalumno',
            name='cursomateria',
        ),
        migrations.DeleteModel(
            name='CursoMateria',
        ),
    ]
