# Generated by Django 5.0.7 on 2024-08-15 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colegio', '0002_categoriaprofesores_localidad_nivelprofesores_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cursomateria',
            name='docente',
        ),
        migrations.AddField(
            model_name='cursomateria',
            name='docentes',
            field=models.ManyToManyField(related_name='curso_materias', to='colegio.docentes'),
        ),
    ]
