# Generated by Django 5.0.7 on 2024-08-16 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colegio', '0003_remove_notas_id_cursomateria_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CursoMateria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colegio.curso')),
                ('docentes', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='colegio.docentes')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colegio.materia')),
            ],
        ),
    ]
