# Generated by Django 5.0.7 on 2024-08-15 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colegio', '0003_remove_cursomateria_docente_cursomateria_docentes'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariorol',
            name='docente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='colegio.docentes'),
        ),
    ]
