# Generated by Django 5.0.7 on 2024-07-30 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colegio', '0003_auto_20240730_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docentes',
            name='cuil',
            field=models.IntegerField(),
        ),
    ]
