# Generated by Django 5.0.7 on 2024-07-30 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colegio', '0004_alter_docentes_cuil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docentes',
            name='celular_mama',
        ),
        migrations.AddField(
            model_name='docentes',
            name='numero_legajo_sueldo',
            field=models.IntegerField(default='00'),
        ),
        migrations.AddField(
            model_name='docentes',
            name='telefono',
            field=models.IntegerField(default='00'),
        ),
        migrations.AlterField(
            model_name='docentes',
            name='horario',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='docentes',
            name='legajo_administrativo',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='docentes',
            name='legajo_reloj',
            field=models.IntegerField(),
        ),
    ]
