# Generated by Django 5.0.7 on 2024-08-16 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colegio', '0005_notas_id_cursomateria'),
    ]

    operations = [
        migrations.AddField(
            model_name='materiaalumno',
            name='id_cursomateria',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='colegio.cursomateria'),
        ),
    ]
