# Generated by Django 5.0.7 on 2024-07-30 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colegio', '0006_rename_correo_electronico_alumnos_correo_electronico_institucional'),
    ]

    operations = [
    ]
