# Generated by Django 5.0.7 on 2024-08-16 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colegio', '0006_materiaalumno_id_cursomateria'),
    ]

    operations = [
    ]
