# Generated by Django 5.0.7 on 2024-07-31 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colegio', '0007_auto_20240730_1127'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alumnos',
            old_name='Correo_Electronico_institucional',
            new_name='Correo_Electronico_Institucional',
        ),
        migrations.RenameField(
            model_name='alumnos',
            old_name='Correo_Electronico_particular',
            new_name='Correo_Electronico_Particular',
        ),
        migrations.RemoveField(
            model_name='docentes',
            name='cursos',
        ),
        migrations.RemoveField(
            model_name='docentes',
            name='materia',
        ),
        migrations.CreateModel(
            name='CursoMateria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colegio.curso')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colegio.materia')),
            ],
        ),
        migrations.CreateModel(
            name='DocenteCursoMateria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cursomateria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colegio.cursomateria')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colegio.docentes')),
            ],
            options={
                'unique_together': {('profesor', 'cursomateria')},
            },
        ),
        migrations.CreateModel(
            name='Matriculas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=255)),
                ('id_alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colegio.alumnos')),
            ],
        ),
        migrations.CreateModel(
            name='NotasPrimerTrimestre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PROCESO', models.FloatField(blank=True, null=True)),
                ('PARTICIPACION_EN_CLASE', models.FloatField(blank=True, null=True)),
                ('TP_INDIVIDUAL_1', models.FloatField(blank=True, null=True)),
                ('TP_INDIVIDUAL_2', models.FloatField(blank=True, null=True)),
                ('LECCION_ORAL_INDIVIDUAL', models.FloatField(blank=True, null=True)),
                ('EXPOSICION_ORAL_INDIVIDUAL', models.FloatField(blank=True, null=True)),
                ('EVALUACION_ESCRITA', models.FloatField(blank=True, null=True)),
                ('EXPOSICION_GRUPAL_NOTA_GRUPAL', models.FloatField(blank=True, null=True)),
                ('EXPOSICION_GRUPAL_NOTA_INDIVIDUAL', models.FloatField(blank=True, null=True)),
                ('EXPOSICION_GRUPAL_SOPORTE_PRESENTACION', models.FloatField(blank=True, null=True)),
                ('LABORATORIO_Y_TALLER', models.FloatField(blank=True, null=True)),
                ('CARPETA', models.FloatField(blank=True, null=True)),
                ('MATERIAL', models.FloatField(blank=True, null=True)),
                ('CONDUCTA', models.CharField(max_length=50)),
                ('id_docentecursomateria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colegio.docentecursomateria')),
                ('id_matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colegio.matriculas')),
            ],
        ),
    ]
