# Generated by Django 5.0.7 on 2024-07-31 22:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colegio', '0008_rename_correo_electronico_institucional_alumnos_correo_electronico_institucional_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notasprimertrimestre',
            old_name='EXPOSICION_GRUPAL_NOTA_GRUPAL',
            new_name='EXPOSICION1_GRUPAL_NOTA_GRUPAL',
        ),
        migrations.RenameField(
            model_name='notasprimertrimestre',
            old_name='EXPOSICION_GRUPAL_NOTA_INDIVIDUAL',
            new_name='EXPOSICION1_GRUPAL_NOTA_INDIVIDUAL',
        ),
        migrations.RenameField(
            model_name='notasprimertrimestre',
            old_name='EXPOSICION_GRUPAL_SOPORTE_PRESENTACION',
            new_name='EXPOSICION1_GRUPAL_SOPORTE_PRESENTACION',
        ),
        migrations.AddField(
            model_name='notasprimertrimestre',
            name='EXPOSICION2_GRUPAL_NOTA_GRUPAL',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notasprimertrimestre',
            name='EXPOSICION2_GRUPAL_NOTA_INDIVIDUAL',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notasprimertrimestre',
            name='EXPOSICION2_GRUPAL_SOPORTE_PRESENTACION',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='NotasSegundoTrimestre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PROCESO', models.FloatField(blank=True, null=True)),
                ('PARTICIPACION_EN_CLASE', models.FloatField(blank=True, null=True)),
                ('TP_INDIVIDUAL_1', models.FloatField(blank=True, null=True)),
                ('TP_INDIVIDUAL_2', models.FloatField(blank=True, null=True)),
                ('LECCION_ORAL_INDIVIDUAL', models.FloatField(blank=True, null=True)),
                ('EXPOSICION_ORAL_INDIVIDUAL', models.FloatField(blank=True, null=True)),
                ('EVALUACION_ESCRITA', models.FloatField(blank=True, null=True)),
                ('EXPOSICION1_GRUPAL_NOTA_GRUPAL', models.FloatField(blank=True, null=True)),
                ('EXPOSICION1_GRUPAL_NOTA_INDIVIDUAL', models.FloatField(blank=True, null=True)),
                ('EXPOSICION1_GRUPAL_SOPORTE_PRESENTACION', models.FloatField(blank=True, null=True)),
                ('EXPOSICION2_GRUPAL_NOTA_GRUPAL', models.FloatField(blank=True, null=True)),
                ('EXPOSICION2_GRUPAL_NOTA_INDIVIDUAL', models.FloatField(blank=True, null=True)),
                ('EXPOSICION2_GRUPAL_SOPORTE_PRESENTACION', models.FloatField(blank=True, null=True)),
                ('LABORATORIO_Y_TALLER', models.FloatField(blank=True, null=True)),
                ('CARPETA', models.FloatField(blank=True, null=True)),
                ('MATERIAL', models.FloatField(blank=True, null=True)),
                ('CONDUCTA', models.CharField(max_length=50)),
                ('id_docentecursomateria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colegio.docentecursomateria')),
                ('id_matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colegio.matriculas')),
            ],
        ),
        migrations.CreateModel(
            name='NotasTercerTrimestre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PROCESO', models.FloatField(blank=True, null=True)),
                ('PARTICIPACION_EN_CLASE', models.FloatField(blank=True, null=True)),
                ('TP_INDIVIDUAL_1', models.FloatField(blank=True, null=True)),
                ('TP_INDIVIDUAL_2', models.FloatField(blank=True, null=True)),
                ('LECCION_ORAL_INDIVIDUAL', models.FloatField(blank=True, null=True)),
                ('EXPOSICION_ORAL_INDIVIDUAL', models.FloatField(blank=True, null=True)),
                ('EVALUACION_ESCRITA', models.FloatField(blank=True, null=True)),
                ('EXPOSICION1_GRUPAL_NOTA_GRUPAL', models.FloatField(blank=True, null=True)),
                ('EXPOSICION1_GRUPAL_NOTA_INDIVIDUAL', models.FloatField(blank=True, null=True)),
                ('EXPOSICION1_GRUPAL_SOPORTE_PRESENTACION', models.FloatField(blank=True, null=True)),
                ('EXPOSICION2_GRUPAL_NOTA_GRUPAL', models.FloatField(blank=True, null=True)),
                ('EXPOSICION2_GRUPAL_NOTA_INDIVIDUAL', models.FloatField(blank=True, null=True)),
                ('EXPOSICION2_GRUPAL_SOPORTE_PRESENTACION', models.FloatField(blank=True, null=True)),
                ('LABORATORIO_Y_TALLER', models.FloatField(blank=True, null=True)),
                ('CARPETA', models.FloatField(blank=True, null=True)),
                ('MATERIAL', models.FloatField(blank=True, null=True)),
                ('CONDUCTA', models.CharField(max_length=50)),
                ('id_docentecursomateria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colegio.docentecursomateria')),
                ('id_matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colegio.matriculas')),
            ],
        ),
    ]
