# Generated by Django 5.0.7 on 2024-08-01 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colegio', '0009_rename_exposicion_grupal_nota_grupal_notasprimertrimestre_exposicion1_grupal_nota_grupal_and_more'),
    ]

    operations = [
    ]
