# Generated by Django 5.0.7 on 2024-08-02 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colegio', '0011_alumnos_fecha_creacion_alumnos_fecha_modificacion_and_more'),
    ]

    operations = [
    ]
