# Generated by Django 5.0.7 on 2024-08-02 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colegio', '0012_auto_20240802_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursomateria',
            name='docente',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='colegio.docentes'),
        ),
    ]
