# Generated by Django 5.0.7 on 2024-08-02 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colegio', '0013_cursomateria_docente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colegio.alumnos')),
                ('cursomateria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colegio.cursomateria')),
            ],
        ),
    ]
