# Generated by Django 5.0.7 on 2024-08-02 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colegio', '0015_actividadescalificadas_notas_nota_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notas',
            name='actividades_calificadas',
        ),
        migrations.DeleteModel(
            name='ActividadesCalificadas',
        ),
    ]
