# Generated by Django 5.0.7 on 2024-08-02 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colegio', '0016_remove_notas_actividades_calificadas_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notasprimertrimestre',
            name='id_docentecursomateria',
        ),
        migrations.RemoveField(
            model_name='notassegundotrimestre',
            name='id_docentecursomateria',
        ),
        migrations.RemoveField(
            model_name='notastercertrimestre',
            name='id_docentecursomateria',
        ),
        migrations.AddField(
            model_name='notasprimertrimestre',
            name='id_cursomateria',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='colegio.cursomateria'),
        ),
        migrations.AddField(
            model_name='notassegundotrimestre',
            name='id_cursomateria',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='colegio.cursomateria'),
        ),
        migrations.AddField(
            model_name='notastercertrimestre',
            name='id_cursomateria',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='colegio.cursomateria'),
        ),
        migrations.DeleteModel(
            name='DocenteCursoMateria',
        ),
    ]
