# Generated by Django 5.0.7 on 2024-08-03 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colegio', '0017_remove_notasprimertrimestre_id_docentecursomateria_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notas',
            name='nota',
        ),
    ]
