# Generated by Django 5.0.7 on 2024-08-03 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colegio', '0018_remove_notas_nota'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notasprimertrimestre',
            name='id_cursomateria',
        ),
        migrations.AddField(
            model_name='notasprimertrimestre',
            name='id_notas',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='colegio.notas'),
        ),
    ]
