# Generated by Django 5.0.7 on 2024-08-05 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colegio', '0019_remove_notasprimertrimestre_id_cursomateria_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='familias',
            old_name='id_familia',
            new_name='id',
        ),
    ]
