# Generated by Django 5.0.7 on 2024-08-05 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colegio', '0020_rename_id_familia_familias_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumnos',
            name='id_matricula',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='colegio.matriculas', verbose_name='Matricula'),
        ),
    ]
