# Generated by Django 5.0.7 on 2024-08-05 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colegio', '0021_alumnos_id_matricula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnos',
            name='id_matricula',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='colegio.matriculas', verbose_name='Matricula'),
        ),
    ]
