# Generated by Django 5.0.7 on 2024-08-05 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colegio', '0022_alter_alumnos_id_matricula'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumnos',
            name='id_matricula',
        ),
    ]
