# Generated by Django 5.0.7 on 2024-08-05 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colegio', '0024_auto_20240805_1112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notasprimertrimestre',
            name='id_notas',
        ),
        migrations.AddField(
            model_name='notasprimertrimestre',
            name='id_cursomateria',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='colegio.cursomateria'),
        ),
        migrations.DeleteModel(
            name='Notas',
        ),
    ]
