# Generated by Django 5.0.7 on 2024-08-05 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colegio', '0025_remove_notasprimertrimestre_id_notas_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notassegundotrimestre',
            name='id_cursomateria',
        ),
        migrations.RemoveField(
            model_name='notassegundotrimestre',
            name='id_matricula',
        ),
        migrations.RemoveField(
            model_name='notastercertrimestre',
            name='id_cursomateria',
        ),
        migrations.RemoveField(
            model_name='notastercertrimestre',
            name='id_matricula',
        ),
        migrations.CreateModel(
            name='Notas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trimestre', models.IntegerField(choices=[(1, 'Primer Trimestre'), (2, 'Segundo Trimestre'), (3, 'Tercer Trimestre')])),
                ('PROCESO', models.FloatField(blank=True, null=True)),
                ('PARTICIPACION_EN_CLASE', models.FloatField(blank=True, null=True)),
                ('TP_INDIVIDUAL_1', models.FloatField(blank=True, null=True)),
                ('TP_INDIVIDUAL_2', models.FloatField(blank=True, null=True)),
                ('LECCION_ORAL_INDIVIDUAL', models.FloatField(blank=True, null=True)),
                ('EXPOSICION_ORAL_INDIVIDUAL', models.FloatField(blank=True, null=True)),
                ('EVALUACION_ESCRITA', models.FloatField(blank=True, null=True)),
                ('EXPOSICION1_GRUPAL_NOTA_GRUPAL', models.FloatField(blank=True, null=True)),
                ('EXPOSICION1_GRUPAL_NOTA_INDIVIDUAL', models.FloatField(blank=True, null=True)),
                ('EXPOSICION1_GRUPAL_SOPORTE_PRESENTACION', models.FloatField(blank=True, null=True)),
                ('EXPOSICION2_GRUPAL_NOTA_GRUPAL', models.FloatField(blank=True, null=True)),
                ('EXPOSICION2_GRUPAL_NOTA_INDIVIDUAL', models.FloatField(blank=True, null=True)),
                ('EXPOSICION2_GRUPAL_SOPORTE_PRESENTACION', models.FloatField(blank=True, null=True)),
                ('LABORATORIO_Y_TALLER', models.FloatField(blank=True, null=True)),
                ('CARPETA', models.FloatField(blank=True, null=True)),
                ('MATERIAL', models.FloatField(blank=True, null=True)),
                ('CONDUCTA', models.CharField(max_length=50)),
                ('id_cursomateria', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='colegio.cursomateria')),
                ('id_matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colegio.matriculas')),
            ],
        ),
        migrations.DeleteModel(
            name='NotasPrimerTrimestre',
        ),
        migrations.DeleteModel(
            name='NotasSegundoTrimestre',
        ),
        migrations.DeleteModel(
            name='NotasTercerTrimestre',
        ),
    ]
