# Generated by Django 5.0.7 on 2024-08-05 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colegio', '0026_remove_notassegundotrimestre_id_cursomateria_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matriculas',
            name='matricula',
        ),
    ]
