# Generated by Django 5.0.7 on 2024-08-05 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colegio', '0027_remove_matriculas_matricula'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alumnos',
            old_name='id_alumno',
            new_name='id',
        ),
    ]
