# Generated by Django 5.0.7 on 2024-08-05 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colegio', '0028_rename_id_alumno_alumnos_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alumnos',
            old_name='id',
            new_name='id_alumnos',
        ),
    ]
