# Generated by Django 5.0.7 on 2024-08-05 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colegio', '0030_rename_id_alumnos_alumnos_id_alumno'),
    ]

    operations = [
        migrations.CreateModel(
            name='MateriaAlumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cursomateria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colegio.cursomateria')),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colegio.matriculas')),
            ],
        ),
    ]
