# Generated by Django 5.0.6 on 2024-08-06 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colegio', '0031_materiaalumno'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matriculas',
            old_name='fecha_creacion',
            new_name='fecha_creacion_matricula',
        ),
        migrations.RenameField(
            model_name='matriculas',
            old_name='id_alumno',
            new_name='id_alumno_matricula',
        ),
        migrations.AddField(
            model_name='matriculas',
            name='curso_matricula',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='colegio.curso'),
        ),
    ]
